import { useState, useEffect } from 'react';
import Sidebar from './components/Sidebar';
import ChatInterface from './components/ChatInterface';
import { api } from './api';
import './App.css';

import ModelSelector from './components/ModelSelector';
import AnalyticsDashboard from './components/AnalyticsDashboard';

function App() {
  const [conversations, setConversations] = useState([]);
  const [currentConversationId, setCurrentConversationId] = useState(null);
  const [currentConversation, setCurrentConversation] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isModelSelectorOpen, setIsModelSelectorOpen] = useState(false);
  const [showAnalytics, setShowAnalytics] = useState(false);

  // Load conversations on mount
  useEffect(() => {
    loadConversations();
  }, []);

  const loadConversations = async () => {
    try {
      const convs = await api.listConversations();
      setConversations(convs);
    } catch (error) {
      console.error('Failed to load conversations:', error);
    }
  };

  // Load conversation details when selected
  useEffect(() => {
    if (!currentConversationId) return;

    let cancelled = false;

    const loadConversation = async (id) => {
      try {
        const conv = await api.getConversation(id);
        if (!cancelled) {
          setCurrentConversation(conv);
        }
      } catch (error) {
        if (!cancelled) {
          console.error('Failed to load conversation:', error);
          alert('Failed to load conversation');
        }
      }
    };

    loadConversation(currentConversationId);

    return () => {
      cancelled = true;
    };
  }, [currentConversationId]);

  const handleNewConversation = () => {
    setIsModelSelectorOpen(true);
  };

  const handleModelConfirm = async (councilMembers, chairmanModel) => {
    try {
      // Create conversation with selected models
      // Topic is auto-generated by backend later, so we pass null or empty string if API requires it
      // But our API createConversation takes (topic, council, chairman)
      // We can pass a default topic or let backend handle it. 
      // Looking at api.js, it takes (topic, councilMembers, chairmanModel).
      // Let's pass "New Conversation" as initial topic, backend will update it.
      const newConv = await api.createConversation("New Conversation", councilMembers, chairmanModel);

      setConversations([
        { id: newConv.id, created_at: newConv.created_at, message_count: 0 },
        ...conversations,
      ]);
      setCurrentConversationId(newConv.id);
    } catch (error) {
      console.error('Failed to create conversation:', error);
    }
  };

  const handleSelectConversation = (id) => {
    setCurrentConversationId(id);
  };

  const handleSendMessage = async (content) => {
    if (!currentConversationId) return;

    setIsLoading(true);
    try {
      // Optimistically add user message to UI
      const userMessage = { role: 'user', content };

      // Determine mode based on existing messages
      // If we have messages, it's a follow-up chat
      const isFollowUp = currentConversation.messages.length > 0;
      const mode = isFollowUp ? 'chat' : 'council';

      setCurrentConversation((prev) => ({
        ...prev,
        messages: [...prev.messages, userMessage],
      }));

      if (mode === 'council') {
        // Create a partial assistant message for Council process
        const assistantMessage = {
          role: 'assistant',
          stage1: null,
          stage2: null,
          stage3: null,
          metadata: null,
          loading: {
            stage1: false,
            stage2: false,
            stage3: false,
          },
        };

        // Add the partial assistant message
        setCurrentConversation((prev) => ({
          ...prev,
          messages: [...prev.messages, assistantMessage],
        }));
      } else {
        // Create a partial assistant message for Chat
        const assistantMessage = {
          role: 'assistant',
          content: '', // Will be streamed
          loading: {
            chat: true
          }
        };

        // Add the partial assistant message
        setCurrentConversation((prev) => ({
          ...prev,
          messages: [...prev.messages, assistantMessage],
        }));
      }

      // Send message with streaming
      await api.sendMessageStream(currentConversationId, content, (eventType, event) => {
        switch (eventType) {
          case 'stage1_start':
            setCurrentConversation((prev) => {
              const messages = [...prev.messages];
              const lastMsg = messages[messages.length - 1];
              lastMsg.loading.stage1 = true;
              return { ...prev, messages };
            });
            break;

          case 'stage1_complete':
            setCurrentConversation((prev) => {
              const messages = [...prev.messages];
              const lastMsg = messages[messages.length - 1];
              lastMsg.stage1 = event.data;
              lastMsg.loading.stage1 = false;
              return { ...prev, messages };
            });
            break;

          case 'stage2_start':
            setCurrentConversation((prev) => {
              const messages = [...prev.messages];
              const lastMsg = messages[messages.length - 1];
              lastMsg.loading.stage2 = true;
              return { ...prev, messages };
            });
            break;

          case 'stage2_complete':
            setCurrentConversation((prev) => {
              const messages = [...prev.messages];
              const lastMsg = messages[messages.length - 1];
              lastMsg.stage2 = event.data;
              lastMsg.metadata = event.metadata;
              lastMsg.loading.stage2 = false;
              return { ...prev, messages };
            });
            break;

          case 'stage3_start':
            setCurrentConversation((prev) => {
              const messages = [...prev.messages];
              const lastMsg = messages[messages.length - 1];
              lastMsg.loading.stage3 = true;
              return { ...prev, messages };
            });
            break;

          case 'stage3_complete':
            setCurrentConversation((prev) => {
              const messages = [...prev.messages];
              const lastMsg = messages[messages.length - 1];
              lastMsg.stage3 = event.data;
              lastMsg.loading.stage3 = false;
              return { ...prev, messages };
            });
            break;

          case 'chat_start':
            setCurrentConversation((prev) => {
              const messages = [...prev.messages];
              const lastMsg = messages[messages.length - 1];
              lastMsg.loading.chat = true;
              return { ...prev, messages };
            });
            break;

          case 'chat_response':
            setCurrentConversation((prev) => {
              const messages = [...prev.messages];
              const lastMsg = messages[messages.length - 1];
              // event.data is now an object with content and optional reasoning
              if (typeof event.data === 'string') {
                lastMsg.content = event.data;
              } else {
                lastMsg.content = event.data.content;
                if (event.data.reasoning) {
                  lastMsg.reasoning = event.data.reasoning;
                }
              }
              lastMsg.loading.chat = false;
              return { ...prev, messages };
            });
            break;

          case 'title_complete':
            // Reload conversations to get updated title
            loadConversations();
            break;

          case 'complete':
            // Stream complete, reload conversations list
            if (event.data) {
              setCurrentConversation((prev) => ({
                ...prev,
                total_cost: event.data.total_cost,
              }));
            }
            loadConversations();
            setIsLoading(false);
            break;

          case 'error':
            console.error('Stream error:', event.message);
            setIsLoading(false);
            break;

          default:
            console.log('Unknown event type:', eventType);
        }
      }, mode);
    } catch (error) {
      console.error('Failed to send message:', error);

      // Show error to user
      alert(`Failed to send message: ${error.message || 'Unknown error'}`);

      // Safely revert optimistic updates
      setCurrentConversation((prev) => {
        const messages = [...prev.messages];
        // Only remove messages if they were added
        if (messages.length >= 2 && messages[messages.length - 1].role === 'assistant') {
          messages.splice(-2);
        } else if (messages.length >= 1 && messages[messages.length - 1].role === 'user') {
          messages.splice(-1);
        }
        return { ...prev, messages };
      });

      setIsLoading(false);
    }
  };

  return (
    <div className="app">
      <Sidebar
        conversations={conversations}
        currentConversationId={currentConversationId}
        onSelectConversation={handleSelectConversation}
        onNewConversation={handleNewConversation}
        onShowAnalytics={() => setShowAnalytics(true)}
      />
      <ChatInterface
        conversation={currentConversation}
        onSendMessage={handleSendMessage}
        isLoading={isLoading}
      />
      <ModelSelector
        isOpen={isModelSelectorOpen}
        onClose={() => setIsModelSelectorOpen(false)}
        onConfirm={handleModelConfirm}
      />
      {showAnalytics && (
        <AnalyticsDashboard onClose={() => setShowAnalytics(false)} />
      )}
    </div>
  );
}

export default App;
